config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

    validates_presence_of :title
    validates_presence_of :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ] 

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    
    

    @project = Project.new
  end

  # GET /projects/1/edit
  def edit

  end

  # POST /projects or /projects.json
  def create

    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy

    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
      
      <ul class="navbar-nav">

        <a class="navbar-brand" href="/projects">Portfolio Project </a>

          <li class="nav-item active">
            <a class="nav-link" href="/projects">Home <span class="sr-only">(current)</span></a>
          </li>

          


          

      </ul>

      <% if (user_signed_in?) %>

        <form class="form-inline">

          Signed in as: <%= current_user.email %> &nbsp (
          <%= link_to "Log Out", "/users/sign_out", method: :delete %> )
          
        </form>

      <% else %>

        <form class="form-inline">
          <a class="btn btn-outline-success" href="/users/sign_in" role="button">Sign in</a>
        </form>

      <% end %>


    </nav>
    
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="jumbotron text-center">
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<div class="jumbotron text-center">
<p id="notice"><%= notice %></p>

<h1 class="display-4">Welcome to Cole Bennett's Portfolio</h1>

<p class="lead">Computer science major, UCCS</p>
<br>
<h1>Projects</h1>
<br>

<div class = "card-columns">

<% @projects.each do |project| %>
  <tr>

    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">  <%= project.title %>  </h5>
        <p class="card-text">  <%= project.description %>  </p>
        <%= link_to 'View', project %>
        <% if (user_signed_in?) %>
        &nbsp | &nbsp
        <%= link_to 'Edit', edit_project_path(project) %> &nbsp | &nbsp
        <%= link_to 'Remove', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
      </div>
    </div>
  </tr>
<% end %>

</div>

<br>

<% if (user_signed_in?) %>
<%= link_to 'Add New Project', new_project_path %>
<%end%>

</div>

app/views/projects/new.html.erb
<div class="jumbotron text-center">
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

</div>

app/views/projects/show.html.erb
<div class="jumbotron text-center">
    <p id="notice"><%= notice %></p>

    <p>
      <h1 class="display-4"> <%= @project.title %> </h1>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @project.description %>
    </p>

    <% if (user_signed_in?) %>

    <%= link_to 'Edit', edit_project_path(@project) %> &nbsp | &nbsp

    <%end%>
    
    <%= link_to 'Back', projects_path %>
</div>